root: true
plugins:
  - prettier
extends:
  - plugin:prettier/recommended
  - plugin:react/recommended
parser: babel-eslint
settings:
  react:
    version: '16.8.6'
env:
  browser: true
  es6: true
  mocha: true
  node: true
globals:
  "$": true
  inkdrop: true
  app: true
  _settings: true
  _isDemo: true
  _REACT_EXTENSION_PATH: true
  BROWSER: true
  fetch: true
  URL: true
  File: true
  FileReader: true
  Image: true
  btoa: true
  alert: true
  emit: true
rules:
  no-useless-escape: 0
  prettier/prettier:
    - 2
    -
      trailingComma: none
      singleQuote: true
      semi: false
  prefer-const: 2
  no-unused-vars:
    - 2
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  react/display-name: 0
